// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure/repository/sales_insight.go
//
// Generated by this command:
//
//	mockgen -source=infrastructure/repository/sales_insight.go -destination=infrastructure/repository/mocks/mock_sales_insight_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/vfg2006/traffic-manager-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSalesInsightRepository is a mock of SalesInsightRepository interface.
type MockSalesInsightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSalesInsightRepositoryMockRecorder
	isgomock struct{}
}

// MockSalesInsightRepositoryMockRecorder is the mock recorder for MockSalesInsightRepository.
type MockSalesInsightRepositoryMockRecorder struct {
	mock *MockSalesInsightRepository
}

// NewMockSalesInsightRepository creates a new mock instance.
func NewMockSalesInsightRepository(ctrl *gomock.Controller) *MockSalesInsightRepository {
	mock := &MockSalesInsightRepository{ctrl: ctrl}
	mock.recorder = &MockSalesInsightRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSalesInsightRepository) EXPECT() *MockSalesInsightRepositoryMockRecorder {
	return m.recorder
}

// DeleteOlderThan mocks base method.
func (m *MockSalesInsightRepository) DeleteOlderThan(days int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", days)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockSalesInsightRepositoryMockRecorder) DeleteOlderThan(days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockSalesInsightRepository)(nil).DeleteOlderThan), days)
}

// GetByAccountIDAndDate mocks base method.
func (m *MockSalesInsightRepository) GetByAccountIDAndDate(accountID string, date time.Time) (*domain.SalesInsightEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountIDAndDate", accountID, date)
	ret0, _ := ret[0].(*domain.SalesInsightEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountIDAndDate indicates an expected call of GetByAccountIDAndDate.
func (mr *MockSalesInsightRepositoryMockRecorder) GetByAccountIDAndDate(accountID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountIDAndDate", reflect.TypeOf((*MockSalesInsightRepository)(nil).GetByAccountIDAndDate), accountID, date)
}

// GetByDateRange mocks base method.
func (m *MockSalesInsightRepository) GetByDateRange(accountID string, startDate, endDate time.Time) ([]*domain.SalesInsightEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateRange", accountID, startDate, endDate)
	ret0, _ := ret[0].([]*domain.SalesInsightEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateRange indicates an expected call of GetByDateRange.
func (mr *MockSalesInsightRepositoryMockRecorder) GetByDateRange(accountID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateRange", reflect.TypeOf((*MockSalesInsightRepository)(nil).GetByDateRange), accountID, startDate, endDate)
}

// SaveOrUpdate mocks base method.
func (m *MockSalesInsightRepository) SaveOrUpdate(insight *domain.SalesInsightEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrUpdate", insight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrUpdate indicates an expected call of SaveOrUpdate.
func (mr *MockSalesInsightRepositoryMockRecorder) SaveOrUpdate(insight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrUpdate", reflect.TypeOf((*MockSalesInsightRepository)(nil).SaveOrUpdate), insight)
}
