// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure/repository/monthly_sales_insight.go
//
// Generated by this command:
//
//	mockgen -source=infrastructure/repository/monthly_sales_insight.go -destination=infrastructure/repository/mocks/mock_monthly_sales_insight_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/vfg2006/traffic-manager-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMonthlySalesInsightRepository is a mock of MonthlySalesInsightRepository interface.
type MockMonthlySalesInsightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMonthlySalesInsightRepositoryMockRecorder
	isgomock struct{}
}

// MockMonthlySalesInsightRepositoryMockRecorder is the mock recorder for MockMonthlySalesInsightRepository.
type MockMonthlySalesInsightRepositoryMockRecorder struct {
	mock *MockMonthlySalesInsightRepository
}

// NewMockMonthlySalesInsightRepository creates a new mock instance.
func NewMockMonthlySalesInsightRepository(ctrl *gomock.Controller) *MockMonthlySalesInsightRepository {
	mock := &MockMonthlySalesInsightRepository{ctrl: ctrl}
	mock.recorder = &MockMonthlySalesInsightRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonthlySalesInsightRepository) EXPECT() *MockMonthlySalesInsightRepositoryMockRecorder {
	return m.recorder
}

// DeleteOlderThan mocks base method.
func (m *MockMonthlySalesInsightRepository) DeleteOlderThan(months int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", months)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockMonthlySalesInsightRepositoryMockRecorder) DeleteOlderThan(months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockMonthlySalesInsightRepository)(nil).DeleteOlderThan), months)
}

// GetAllPeriods mocks base method.
func (m *MockMonthlySalesInsightRepository) GetAllPeriods() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeriods")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeriods indicates an expected call of GetAllPeriods.
func (mr *MockMonthlySalesInsightRepositoryMockRecorder) GetAllPeriods() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeriods", reflect.TypeOf((*MockMonthlySalesInsightRepository)(nil).GetAllPeriods))
}

// GetByAccountIDAndPeriod mocks base method.
func (m *MockMonthlySalesInsightRepository) GetByAccountIDAndPeriod(accountID string, date time.Time) (*domain.MonthlySalesInsightEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountIDAndPeriod", accountID, date)
	ret0, _ := ret[0].(*domain.MonthlySalesInsightEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountIDAndPeriod indicates an expected call of GetByAccountIDAndPeriod.
func (mr *MockMonthlySalesInsightRepositoryMockRecorder) GetByAccountIDAndPeriod(accountID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountIDAndPeriod", reflect.TypeOf((*MockMonthlySalesInsightRepository)(nil).GetByAccountIDAndPeriod), accountID, date)
}

// GetByPeriodRange mocks base method.
func (m *MockMonthlySalesInsightRepository) GetByPeriodRange(accountID string, startDate, endDate time.Time) ([]*domain.MonthlySalesInsightEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPeriodRange", accountID, startDate, endDate)
	ret0, _ := ret[0].([]*domain.MonthlySalesInsightEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPeriodRange indicates an expected call of GetByPeriodRange.
func (mr *MockMonthlySalesInsightRepositoryMockRecorder) GetByPeriodRange(accountID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPeriodRange", reflect.TypeOf((*MockMonthlySalesInsightRepository)(nil).GetByPeriodRange), accountID, startDate, endDate)
}

// SaveOrUpdate mocks base method.
func (m *MockMonthlySalesInsightRepository) SaveOrUpdate(insight *domain.MonthlySalesInsightEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrUpdate", insight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrUpdate indicates an expected call of SaveOrUpdate.
func (mr *MockMonthlySalesInsightRepositoryMockRecorder) SaveOrUpdate(insight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrUpdate", reflect.TypeOf((*MockMonthlySalesInsightRepository)(nil).SaveOrUpdate), insight)
}
